version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  flower:
    image: mher/flower
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: >
      celery -A core flower
             --broker=redis://redis:6379/0
             --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

  minio:
    image: minio/minio
    ports:
      - "9000:9000"   
      - "9001:9001"   
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  backend:
    build:
      context: ./dormease_server
      dockerfile: Dockerfile
    container_name: django_backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dormease_server:/app  
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
      - minio
    restart: unless-stopped


  frontend:
    build:
      context: ./dormease-front/dormease
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
  minio_data:
