# Generated by Django 5.2 on 2025-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_level",
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.IntegerField(default=6),
        ),
    ]
